on: 
  push:

  workflow_dispatch:
    inputs:

      daemon_debug:
        description: 'Enable or disable the AP daemon debug'
        required: true
        type: choice
        default: "ON"
        options:
          - "ON"
          - "OFF"

      daemon_port:
        description: 'Port for the AP daemon'
        required: true
        type: string
        default: "5000"

      execution_period:
        description: 'Execution period for the AP full pipeline'
        required: true
        type: string
        default: "6h"

name: CI
jobs:
  diff:
    name: diff
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - dependencies: 'src.*one.*cpp|src.*two.*cpp'
            path: src/one
          - dependencies: 'src.*two.*cpp'
            path: src/two
    steps:
      - name: echo vars
        run: |

            echo "${{ inputs.execution_period }}"
            echo "${{ inputs.daemon_port }}"
            echo "${{ inputs.daemon_debug }}"

      # Prepare project repository.
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Check for compilation requirement
        id: test
        run: |
          DIFFS=$(git diff --name-only HEAD origin/${{ github.head_ref }})
          echo $DIFFS
