on:
  pull_request:
  
concurrency:
  group: "branch name"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: delay
        run: sleep 10

      - name: print
        run: echo "hello world"
