on:
  workflow_dispatch:
    inputs:
      daemon_debug:
        description: 'Enable or disable the AP daemon debug'
        required: true
        type: choice
        default: "ON"
        options:
          - "ON"
          - "OFF"

      daemon_port:
        description: 'Port for the AP daemon'
        required: true
        type: string
        default: "5000"

      execution_period:
        description: 'Execution period for the AP full pipeline'
        required: true
        type: string
        default: "6h"

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: print
        env:
          DEBUG: ${{ inputs.daemon_debug }}
          PORT: ${{ inputs.daemon_port }}
          PERIOD: ${{ inputs.execution_period }}
        run: |
          echo "Debug: ${DEBUG}"
          echo "Port: ${PORT}"
          echo "Period: ${PERIOD}"

          echo "Debug: ${{ inputs.daemon_debug }}"
          echo "Port:  ${{ inputs.daemon_port }}"
          echo "Period: ${{ inputs.execution_period }}"
